### ISSUE TITLE
Version tags

### ISSUE THREAD

**Issue by Brixomatic** [visrealm/acme#5]
Hi, 
I'm currently creating my own docker container containing a toolbox.
For that I'm checking out the git repository, building the acme assembler from source.
To be sure that I don't install a version that might contain a "dirty" snapshot of something you might be currently working on, is it possible to set a version tag to those commits that you feel comfortable with as a release?

This way, I could clone the repo, check out the specific version and build it and be sure that the content of the toolbox is not changing without me noticing.

**Comment by visrealm** [comment]
Hi, I recently updated to use CMake. Added GitHub CI builds and tests for Windows and Linux and have tagged the latest release v1.1. I hope that helps.
You can still use the old build system if you prefer.
